version: '3.5'



services:
    app1:
        image: bitnami/nginx
        volumes:
            - D:\Projects\sample_loadbalancer\3_third_try\php_app1\index.php:/app/index.php
            - D:\Projects\sample_loadbalancer\3_third_try\php_app1\app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
        ports:
            - 8081:8080
    php-app1:
        image: bitnami/php-fpm:7.3
        volumes:
            - D:\Projects\sample_loadbalancer\3_third_try\php_app1\index.php:/app/index.php
    app2:
        image: bitnami/nginx
        volumes:
            - D:\Projects\sample_loadbalancer\3_third_try\php_app2\index.php:/app/index.php
            - D:\Projects\sample_loadbalancer\3_third_try\php_app2\app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
        ports:
            - 8082:8080
    php-app2:
        image: bitnami/php-fpm:7.4
        volumes:
            - D:\Projects\sample_loadbalancer\3_third_try\php_app2\index.php:/app/index.php
    balancer:
        build: ./nginx
        ports:
            - 8080:80
        depends_on:
          - app1
          - app2