version: '3.5'



services:
    app1:
        image: bitnami/nginx
        volumes:
            - D:\Projects\sample_loadbalancer\2_second_try\html_app1\index.html:/app/index.html
        ports:
            - 8081:8080
    app2:
        image: bitnami/nginx
        volumes:
            - D:\Projects\sample_loadbalancer\2_second_try\html_app2\index.html:/app/index.html
        ports:
            - 8082:8080
    balancer:
        build: nginx
        ports:
            - 8080:80
        depends_on:
          - app1
          - app2